# Generated by Django 4.0.4 on 2022-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cost', models.CharField(max_length=50, verbose_name='cost')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('miniDescription', models.CharField(max_length=50, verbose_name='miniDescription')),
                ('image', models.CharField(max_length=250, verbose_name='image')),
            ],
        ),
    ]
