# Generated by Django 4.0.4 on 2022-05-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='miniDescription',
        ),
    ]
